# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_names', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('job_desc', models.CharField(max_length=10000)),
                ('job_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('place', models.CharField(max_length=500)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('attendies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendies', to='app.Employee')),
                ('meet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_owner', to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingstatus_meetings', to='app.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('skill_req', models.CharField(max_length=10000)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('proj_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to='app.Employee')),
                ('team', models.ManyToManyField(related_name='project_team', to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=10000)),
                ('created', models.CharField(max_length=30)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='meetingstatus',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingstatus_meetings', to='app.Review'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='topics',
            field=models.ManyToManyField(to='app.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'emp_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set([('name', 'emp_id')]),
        ),
    ]
