# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='app.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='emp_id',
        ),
    ]
