# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171001_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_id',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
